name: Miku Deploy 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "cc8010ab-975e-4348-92dd-823eba266a8d"
          heroku_app_name: "mikumentionallbot" #Must be unique in Heroku
          heroku_email: "asunavcplay@yandex.com"        
